#!/bin/bash

set -xe -o pipefail

useradd --system -m ci
ci_home=/home/ci

apt-get update -qq

apt-get install -y \
  curl \
  apt-transport-https \
  bzip2 \
  ca-certificates \
  ed \
  g++ \
  git \
  mutt \
  openssh-client \
  openssl \
  wget


# Skeleton / dirs
for dir in /home/ci/.ssh/; do
  mkdir -p ${dir}
  chmod ${dir} 700
  chown -R ci:ci ${dir}
done

# Setup Docker & friends
apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo debian-jessie main" > /etc/apt/sources.list.d/docker.list

apt-get update -qq

apt-get install -y \
  docker-engine

usermod -a -G docker,users ci

wget --progress=dot:giga -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.7.0/docker-compose-Linux-x86_64
chmod +x /usr/local/bin/docker-compose

wget --progress=dot:giga -O /usr/local/bin/etcdtool https://github.com/mickep76/etcdtool/releases/download/3.2/etcdtool-3.2-201602171504.linux.x86_64
chmod +x /usr/local/bin/etcdtool

# Final Steps
chown -R ci:ci ${ci_home} /opt /srv
